package com.education.School.model;


import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

//Contact bean class

/*@Entity is used to related java object with MYSQL table.
@Table is used to indicate which  table this class is going to refer.
 If the table name and class name is exactly same then no need to mention table annotation
*/
@Data
@Entity
@Table(name = "contact_msg")
public class Contact extends BaseEntity {
    //Jakarta Validation is used to do the server side validations of user field data
    //@NotBlank: This annotation is used to validate that the input field is not blank
    //@Size: This annotation is used to ensure that field is having that amount of characters
    //@Pattern: It is used to validate the field based on regex expression
    //@Email : It ensures that correct email address is provided in given field

    @Id //id annotation is used to tell JPA that this field is primary key of the table
    @GeneratedValue(strategy = GenerationType.AUTO,generator = "native")
    @GenericGenerator(name="native",strategy = "native")
    //generatedValue is used to tell JPA that its value is automatically generated by DB and strategy is native
    @Column(name = "contact_id") // use this if table col name is different from POJO class variable name
    private int contactId;
    @NotBlank(message = "Name must not be blank")
    @Size(min=3, message= "Name must be at least 3 characters long")
    private String name;
    @NotBlank(message = "Mobile no. must not be blank")
    @Pattern(regexp = "(^$|[0-9]{10})", message= "Mobile no. must be of 10 digits")
    private String mobileNum;
    @NotBlank(message = "Email must not be blank")
    @Email(message= "Please provide a valid email address")
    private String email;
    @NotBlank(message = "Subject must not be blank")
    @Size(min=5, message= "Subject must be at least 5 characters long")
    private String subject;
    @NotBlank(message = "Message must not be blank")
    @Size(min=10, message= "Message must be at least 10 characters long")
    private String message;

    private String status;

    }
